TeletengaBundle\Domain\Entity\Model\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        nickname:
            type: string
            length: 100
        email:
            type: string
            length: 200